- name: Install HTTPD
  yum:
    name: httpd
    state: present

- name: Create {{ document_root }}
  file:
    path: "{{ document_root }}"
    state: directory

- name: Setting Virtual Host
  template:
    src: vhost.conf.j2
    dest: "/etc/httpd/conf.d/{{domain}}.conf"
  notify: restart httpd

- name: Install Remi Repo
  yum:
    name: http://remi.conetix.com.au/enterprise/remi-release-7.rpm
    state: present

- name: Enable PHP 7.0
  yum:
    enablerepo: remi-php70

- name: Install PHP 7.0
  yum:
    name:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    state: present
  notify: restart httpd